/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelilusion.vistas;

import javax.swing.JOptionPane;

/**
 *
 * @author agus
 */
public class frmprincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmprincipal
     */
    public frmprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        matteBorder1 = new javax.swing.border.MatteBorder(null);
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem1acceso = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jRadioButtonMenuItem4reserva = new javax.swing.JRadioButtonMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jRadioButtonMenuItem5huesped = new javax.swing.JRadioButtonMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jRadioButtonMenuItem6habit = new javax.swing.JRadioButtonMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jRadioButtonMenuItem2consulta = new javax.swing.JRadioButtonMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jRadioButtonMenuItem2obser = new javax.swing.JRadioButtonMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jRadioButtonMenuItem2salida = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${iconImage.source}"), this, org.jdesktop.beansbinding.BeanProperty.create("iconImage"));
        bindingGroup.addBinding(binding);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setForeground(new java.awt.Color(0, 51, 255));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N

        jMenu1.setBackground(new java.awt.Color(255, 204, 255));
        jMenu1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setText("Ingresar");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jRadioButtonMenuItem1acceso.setSelected(true);
        jRadioButtonMenuItem1acceso.setText("Acceso");
        jRadioButtonMenuItem1acceso.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jRadioButtonMenuItem1acceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1accesoActionPerformed(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem1acceso);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(255, 204, 255));
        jMenu2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu2.setText("Reserva");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jRadioButtonMenuItem4reserva.setSelected(true);
        jRadioButtonMenuItem4reserva.setText("Formulario de Reserva");
        jRadioButtonMenuItem4reserva.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jRadioButtonMenuItem4reserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem4reservaActionPerformed(evt);
            }
        });
        jMenu2.add(jRadioButtonMenuItem4reserva);

        jMenuBar1.add(jMenu2);

        jMenu4.setBackground(new java.awt.Color(255, 204, 255));
        jMenu4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu4.setText("Huésped");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jRadioButtonMenuItem5huesped.setSelected(true);
        jRadioButtonMenuItem5huesped.setText("Formulario Huésped");
        jRadioButtonMenuItem5huesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem5huespedActionPerformed(evt);
            }
        });
        jMenu4.add(jRadioButtonMenuItem5huesped);

        jMenuBar1.add(jMenu4);

        jMenu5.setBackground(new java.awt.Color(255, 204, 255));
        jMenu5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu5.setText("Habitación");

        jRadioButtonMenuItem6habit.setSelected(true);
        jRadioButtonMenuItem6habit.setText("Formulario Habitación");
        jRadioButtonMenuItem6habit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jRadioButtonMenuItem6habit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem6habitActionPerformed(evt);
            }
        });
        jMenu5.add(jRadioButtonMenuItem6habit);

        jMenuBar1.add(jMenu5);

        jMenu6.setBackground(new java.awt.Color(255, 204, 255));
        jMenu6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu6.setText("Consultas");

        jRadioButtonMenuItem2consulta.setSelected(true);
        jRadioButtonMenuItem2consulta.setText("Formulario de Consulta");
        jRadioButtonMenuItem2consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2consultaActionPerformed(evt);
            }
        });
        jMenu6.add(jRadioButtonMenuItem2consulta);

        jMenuBar1.add(jMenu6);

        jMenu3.setBackground(new java.awt.Color(255, 204, 255));
        jMenu3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu3.setText("Observaciones");

        jRadioButtonMenuItem2obser.setSelected(true);
        jRadioButtonMenuItem2obser.setText("Formulario de Observaciones");
        jRadioButtonMenuItem2obser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2obserActionPerformed(evt);
            }
        });
        jMenu3.add(jRadioButtonMenuItem2obser);

        jMenuBar1.add(jMenu3);

        jMenu7.setBackground(new java.awt.Color(255, 204, 255));
        jMenu7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu7.setText("Salir");
        jMenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu7ActionPerformed(evt);
            }
        });

        jRadioButtonMenuItem2salida.setSelected(true);
        jRadioButtonMenuItem2salida.setText("¿Esta seguro que desea salir del Sistema?");
        jRadioButtonMenuItem2salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2salidaActionPerformed(evt);
            }
        });
        jMenu7.add(jRadioButtonMenuItem2salida);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonMenuItem1accesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1accesoActionPerformed
        Llamar();
    }//GEN-LAST:event_jRadioButtonMenuItem1accesoActionPerformed

    private void jRadioButtonMenuItem4reservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem4reservaActionPerformed
        Llamar2();
        
    }//GEN-LAST:event_jRadioButtonMenuItem4reservaActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }
     
       private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {  
           
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu7ActionPerformed
        
    }//GEN-LAST:event_jMenu7ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jRadioButtonMenuItem5huespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem5huespedActionPerformed
        Llamar3();
    }//GEN-LAST:event_jRadioButtonMenuItem5huespedActionPerformed

    private void jRadioButtonMenuItem6habitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem6habitActionPerformed
        Llamar4();
    }//GEN-LAST:event_jRadioButtonMenuItem6habitActionPerformed

    private void jRadioButtonMenuItem2consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2consultaActionPerformed
        // TODO add your handling code here:
        Llamar5();
    }//GEN-LAST:event_jRadioButtonMenuItem2consultaActionPerformed

    private void jRadioButtonMenuItem2obserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2obserActionPerformed
        // TODO add your handling code here:
        Llamar6();
    }//GEN-LAST:event_jRadioButtonMenuItem2obserActionPerformed

    private void jRadioButtonMenuItem2salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2salidaActionPerformed
        // TODO add your handling code here:
        Salir();
    }//GEN-LAST:event_jRadioButtonMenuItem2salidaActionPerformed

    
     private void JRadioButtonMenuItem2consultaActionPerformed(java.awt.event.ActionEvent evt) {
         
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmprincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1acceso;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2consulta;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2obser;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2salida;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4reserva;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem5huesped;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem6habit;
    private javax.swing.border.MatteBorder matteBorder1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    private void Llamar(){
        JOptionPane.showMessageDialog(null, "Ha seleccionado el portal de acceso");
        new frmacceso().setVisible(true);
            }
    
    private void Llamar2() {
        JOptionPane.showMessageDialog(null, "Ha seleccionado el Formulario de Reserva");
        new frmreserva().setVisible(true);
    }

    
    private void Salir() {
        
        System.exit(1);
    }
    
    private void Llamar3() {
        JOptionPane.showMessageDialog(null, "Ha seleccionado el Formulario Huésped");
        new frmhuesped().setVisible(true);
    }
    
    private void Llamar4() {
        JOptionPane.showMessageDialog(null, "Ha seleccionado el Formulario Habitación");
        new frmhabitacion().setVisible(true);
    }
    
    private void Llamar5() {
        JOptionPane.showMessageDialog(null, "Ha seleccionado el Formulario de Consulta");
        new frmconsultas().setVisible(true);
    }
    
    private void Llamar6() {
        JOptionPane.showMessageDialog(null, " Acceda al panel de observaciones");
        new frmobservaciones().setVisible(true);
    }
}
